import Head from 'next/head'
import Card from "../components/Card/Card";
import styles from '../styles/Home.module.css'
import {dehydrate, QueryClient} from "@tanstack/react-query";
import {fetchData, QUERY_KEY} from "../utils/api";

export const getServerSideProps = async () => {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(QUERY_KEY, fetchData)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card />
    </div>
  )
}
